### ISSUE TITLE
Daily updates and data consistency

### ISSUE THREAD

**Issue by soshial** [Davis-Klavins/osm-latvia-bot#1]
Thanks a lot for your work, @Davis-Klavins!

I have some questions for you if you don't mind:
1. Because of imagery offset some buildings were mapped with their position shifted from the real one (see screenshot below). During the initial address import the GPS position of an address point (from the State Address Register) turned out to be outside of building borders, like this: <img width="973" alt="Screenshot 2022-06-30 at 10 48 53" src="https://user-images.githubusercontent.com/100644/176623516-991afaba-e4d4-4cc3-a4e5-4588a91cb1eb.png">
**The question is**: what would happen, if some mapper moves building to the correct position (slightly to the right, for example), would your script merge the building with the address point the next day?

2. Another situation: the script merged a building and an address point, but then some day some user moves the building so that the address exact GPS location (from the State Address Register) is outside of the new building borders. **The question is**: would your script extract the address from that building and put it back to the correct GPS location outside of the building borders?

**Comment by Davis-Klavins** [comment]
1. Yes, it will _merge the building with the address point the next day_ (address tags will be assigned to the building and removed from the address point deleting node if it had only address tags).
2. Yes, it will _extract the address from that building and put it back to the correct GPS location outside of the building borders_ (address tags from the building will be removed and a new node created at the location of the address point containing address tags).

**Comment by soshial** [comment]
Labs veikums, paldies tev! Mums visiem tiesam adresu truka

PS. Could you please add this info from your answer into the README?

**Comment by Davis-Klavins** [comment]
I will add extended description of operating principles at https://wiki.openstreetmap.org/wiki/Automated_edits/Latvia-bot later.

**Comment by Davis-Klavins** [comment]
Added: https://wiki.openstreetmap.org/wiki/Automated_edits/Latvia-bot#Why_sometimes_address_points_are_located_near_building_instead_of_address_tags_being_added_to_the_building_itself?
