### ISSUE TITLE
Cannot get VDB_OBJEKTI.xlsx

### ISSUE THREAD

**Issue by i-ky** [Davis-Klavins/osm-latvia-bot#11]
I am looking at these lines
https://github.com/Davis-Klavins/osm-latvia-bot/blob/f20f74e3e57ef0191fe67748c1e1303ef319cdaa/osm_initial.sh#L24-L26
and these lines
https://github.com/Davis-Klavins/osm-latvia-bot/blob/f20f74e3e57ef0191fe67748c1e1303ef319cdaa/lgia_vdb.sh#L15-L17
and trying to run these commands line by line.

It seems that the link scripts are looking for was removed from https://www.lgia.gov.lv/lv/vietvardu-dati-atvertajos-datos, because the following command returns nothing:
```bash
wget -q -O - https://www.lgia.gov.lv/lv/place-names-data-open-data | grep -o '<a href="https://s3.storage.pub.lvdc.gov.lv/lgia-opendata/citi/vdb/.*.xlsx".*>'
```
I've found `.xlsx` file by looking for ["Vietvārdu datu bāze"](https://data.gov.lv/dati/lv/dataset/vietvrdu-datu-bze82) on https://data.gov.lv/, then following to https://geolatvija.lv/geo/p/303 and then clicking the "Vietvārdu dati .csv formātā" link. The link (https://s3.storage.pub.lvdc.gov.lv/lgia-opendata/citi/vdb/VDB_OBJEKTI_02042022.xlsx) seems to match the regular expression from the scripts.

Unfortunately, the link to the file cannot be extracted from https://geolatvija.lv/geo/p/303 with, because the content is not static, there seems to be some Javascript involved. The following command also returns nothing:
```bash
wget -q -O - https://geolatvija.lv/geo/p/303 | grep -o '<a href="https://s3.storage.pub.lvdc.gov.lv/lgia-opendata/citi/vdb/.*.xlsx".*>'
```

**Comment by i-ky** [comment]
Funny, enough, the link is still present in the [English version](https://www.lgia.gov.lv/en/place-name-data-open-data). Now knowing where the link is expected to be and looking at that place in [Latvian version](https://www.lgia.gov.lv/lv/vietvardu-dati-atvertajos-datos), there is a text:
> Vietvārdu dati .csv formātā tiek precizēti

Maybe it is a temporary problem...

**Comment by Davis-Klavins** [comment]
Yes, it's temporarily unavailable. Not a good data publishing practice, though. Changed to English page.
