### ISSUE TITLE
Sanitize multiple spaces in street names

### ISSUE THREAD

**Issue by HellMapGoesCoding** [Davis-Klavins/osm-latvia-bot#5]
There appear to be some addresses in cadaster with whitespace typos between `addr:street` main name part and "iela" suffix, for example:

https://www.openstreetmap.org/way/40585292/history <pre>Aleksandra Druviņa  iela</pre>

https://www.openstreetmap.org/way/40743473/history <pre>Pētera Aulmaņa  iela</pre>

https://www.openstreetmap.org/way/40764752/history <pre>Viļa Januma  iela</pre>

I think it would be reasonably to replace multi-spaces with a single space until such time that VZD data is fixed.

I have not seen this in other values, but it is probably reasonable to sanitize this for all fields just in case?

**Comment by Davis-Klavins** [comment]
Thanks for noting! Corrected:
https://github.com/Davis-Klavins/osm-latvia-bot/commit/f0e41cd7cdf48a6ff13d849c32c76586601843e6
https://github.com/Davis-Klavins/osm-latvia-bot/commit/604b5d6c0efd75578e67a1c05af0df1c6962f3e1
https://www.openstreetmap.org/changeset/128301689
