### ISSUE TITLE
`osm_1.sh` downloads `tags_4_addresses.csv` from GitHub instead of using local copy

### ISSUE THREAD

**Issue by i-ky** [Davis-Klavins/osm-latvia-bot#6]
The following line explicitly pulls a file from GitHub:
https://github.com/Davis-Klavins/osm-latvia-bot/blob/604b5d6c0efd75578e67a1c05af0df1c6962f3e1/osm_1.sh#L14
Why is it needed? I am assuming that whoever runs this script has already cloned the repo and has this file locally.

**Comment by Davis-Klavins** [comment]
To avoid `git pull` each time script is run. Being a data file, it might change more often than other repository files eventually. But it can be done vice versa, of course. Checking if file has been modified to avoid unnecessary downloading and replacing of data in the table would be nice but it's not binding.

**Comment by i-ky** [comment]
> To avoid `git pull` each time script is run.

Why does it need to be avoided?

> Being a data file, it might change more often than other repository files eventually.

It is normal, in every repository there are files that change more often than others.

> Checking if file has been modified to avoid unnecessary downloading...

It is not the downloading that concerns me, but the source URL. It has `Davis-Klavins/osm-latvia-bot` hard coded in it. For example, if I fork your repo, I would prefer for scripts to download from `i-ky/osm-latvia-bot` instead. If I just `git clone` the repo and modify the file, I would like scripts to use the local copy with my modifications.

**Comment by Davis-Klavins** [comment]
Would suggestion reading [Automated Edits code of conduct](https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct). Bot needs a separate user account. Performing the same task from different accounts would be a chaos. Linking that file to a specific GitHub account is OK in this case as it's a global configuration for tags that allow object to have address tags in Latvia.
In the future, fully automated process would be nice but it needs a dedicated server. Also code must be improved to include some error checking in the execution of scripts to avoid damaged data. When it will be fully automated, I plan to give access to some trusted OSM members to this repository in case [tags_4_addresses.csv](tags_4_addresses.csv), links to the source data etc. must been changed.

**Comment by i-ky** [comment]
> Would suggestion reading [Automated Edits code of conduct](https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct). Bot needs a separate user account. Performing the same task from different accounts would be a chaos.

Thank you for pointing this out, but I am not talking about actually uploading anything to osm.org using my working copy of the repo. I am talking about running scripts to produce some sort of intermediate results for manual review during development and testing. Sorry, I have not dug deep into operation of the bot, but I assume there is some way to stop the process before actual upload to osm.org, otherwise it would be very difficult to do development and testing.

> Linking that file to a specific GitHub account is OK in this case as it's a global configuration for tags that allow object to have address tags in Latvia.

Let me disagree. Hopefully, you are going to have contributors with their forks and branches, so code needs to be portable.

> In the future, fully automated process would be nice but it needs a dedicated server.

This is an off-topic, but I would be glad to help you with [GitHub Actions](https://docs.github.com/en/actions) or [Travis CI](https://www.travis-ci.com/) setup for this.

> Also code must be improved to include some error checking in the execution of scripts to avoid damaged data. When it will be fully automated, I plan to give access to some trusted OSM members to this repository in case [tags_4_addresses.csv](tags_4_addresses.csv), links to the source data etc. must been changed.

I imagine these "trusted OSM members" would appreciate the possibility to test their changes locally before pushing them to GitHub. Otherwise `git log` will be polluted with "try this" and "try that" messages.

**Comment by Davis-Klavins** [comment]
OK, convinced as you have more experience in Git: https://github.com/Davis-Klavins/osm-latvia-bot/commit/3deb19cb093debb4d2299d08e3c5a653712dfe15

> I assume there is some way to stop the process before actual upload to osm.org, otherwise it would be very difficult to do development and testing.

Sure, just don't run [osm_3.sh](https://github.com/Davis-Klavins/osm-latvia-bot/blob/main/osm_3.sh). Ability to execute SQL against OSM data and combine it with other data sources gives a lot of opportunities.

> This is an off-topic, but I would be glad to help you with [GitHub Actions](https://docs.github.com/en/actions) or [Travis CI](https://www.travis-ci.com/) setup for this.

OK, I'll keep that in mind.

> I imagine these "trusted OSM members" would appreciate the possibility to test their changes locally before pushing them to GitHub. Otherwise git log will be polluted with "try this" and "try that" messages.

Separating [tags_4_addresses.csv](https://github.com/Davis-Klavins/osm-latvia-bot/issues/tags_4_addresses.csv) in a different repository and using as a submodule probably would be a better solution as it would be possible to give editing rights to just that one file to some other members to better ensure that it gets maintained in the future as a one central file to host these tags.

**Comment by i-ky** [comment]
> OK, convinced as you have more experience in Git: [3deb19c](https://github.com/Davis-Klavins/osm-latvia-bot/commit/3deb19cb093debb4d2299d08e3c5a653712dfe15)

It definitely looks better, because it no longer references this particular repo (so it is already much more fork-friendly), but it still references `main` branch:
https://github.com/Davis-Klavins/osm-latvia-bot/blob/61edf13de7b4ae49b910efb275a40ebd3ae78721/osm_1.sh#L13-L14

If I will be working on a branch I would not want the script to do `git pull` from `main`, especially if my branch has conflicting uncommitted changes. I think the script should just use `tags_4_addresses.csv` as it is on disk and let users to do `git` stuff when and how they want it.

**Comment by i-ky** [comment]
> Separating [tags_4_addresses.csv](https://github.com/Davis-Klavins/osm-latvia-bot/issues/tags_4_addresses.csv) in a different repository and using as a submodule probably would be a better solution as it would be possible to give editing rights to just that one file to some other members to better ensure that it gets maintained in the future as a one central file to host these tags.

This can definitely be an option. For example, [StreetComplete](https://github.com/streetcomplete/StreetComplete) has [metadata repo](https://github.com/streetcomplete/countrymetadata) which allows contributors to tune the application without seeing any code whatsoever. But many projects store metadata in the same repo and simply channel contributors to beginner-friendly contribution points via readme, [contribution guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors), documentation, etc.

**Comment by Davis-Klavins** [comment]
> If I will be working on a branch I would not want the script to do `git pull` from `main`, especially if my branch has conflicting uncommitted changes. I think the script should just use `tags_4_addresses.csv` as it is on disk and let users to do `git` stuff when and how they want it.

OK, commented that line and edited [README](https://github.com/Davis-Klavins/osm-latvia-bot/blob/main/README.md#osm-data-update) to point out that it has to be uncommented in production.
