### ISSUE TITLE
Mention address rules specific to Latvia in OSM Wiki

### ISSUE THREAD

**Issue by i-ky** [Davis-Klavins/osm-latvia-bot#8]
Would be nice to add a short mention of the bot and respective rules (no manual edits etc.) here:
https://wiki.openstreetmap.org/wiki/Addresses#Country_specific_rules_and_sources

I believe Norway can be used as an example, our situation seems to be similar to ours.

**Comment by Davis-Klavins** [comment]
Added: https://wiki.openstreetmap.org/wiki/Addresses#Latvia
